### ISSUE TITLE
Doesnt work with 1.9

### ISSUE THREAD

**Issue by Phreag** [LogBlock/LogBlock#659]
Seems to use an old removed Method...

[11:33:52] [Craft Scheduler Thread - 8/WARN]: org.apache.commons.lang.UnhandledException: Plugin LogBlock v1.94 generated an exception while executing task 38
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at de.diddiz.LogBlock.Metrics.postPlugin(Metrics.java:324)
	at de.diddiz.LogBlock.Metrics.access$400(Metrics.java:46)
	at de.diddiz.LogBlock.Metrics$1.run(Metrics.java:212)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by frymaster** [comment]
Yes, they removed support for a couple of methods from the 1.7 API.  The fix isn't too hard - it's been submitted before in fact, but I didn't see the point in updating the minimum required version if we weren't also adding features. Well, now there is a point :D

**Comment by frymaster** [comment]
...and in fact #658 has already been submitted and will be merged shortly

**Comment by frymaster** [comment]
fixed in 1f1483efab5c6ad938c370513e9b51ab679bcb46

You can download the latest snapshots from http://ci.md-5.net/job/LogBlock/
